In [1]:
# https://stackoverflow.com/questions/39299838/how-do-i-import-module-in-jupyter-notebook-directory-into-notebooks-in-lower-dir
# https://stackoverflow.com/questions/68572852/import-local-modules-in-jupyter-notebook
import os
import sys
# os.path.split(os.getcwd())[0]
sys.path.append("/gpfs/home/dhuang/thesis/WavCaps/retrieval/models")
sys.path.append("/gpfs/home/dhuang/thesis/WavCaps/retrieval/tools")
for nb_dir in sys.path:
    print(nb_dir)
    # sys.path.append(nb_dir)


/gpfs/home/dhuang/thesis/WavCaps
/home/dhuang/.conda/envs/fs/lib/python310.zip
/home/dhuang/.conda/envs/fs/lib/python3.10
/home/dhuang/.conda/envs/fs/lib/python3.10/lib-dynload

/home/dhuang/.conda/envs/fs/lib/python3.10/site-packages
/home/dhuang/.conda/envs/fs/lib/python3.10/site-packages/huggingface_hub-0.14.1-py3.8.egg
/home/dhuang/.conda/envs/fs/lib/python3.10/site-packages/mpmath-1.2.1-py3.10.egg
/home/dhuang/.conda/envs/fs/lib/python3.10/site-packages/sentencepiece-0.1.95-py3.10-linux-x86_64.egg
/gpfs/home/dhuang/thesis/WavCaps/retrieval/models
/gpfs/home/dhuang/thesis/WavCaps/retrieval/tools


In [1]:
import torch.nn as nn
from transformers import (
    BertModel,
    BertTokenizer,
    GPT2Model,
    GPT2Tokenizer,
    RobertaModel,
    RobertaTokenizer,
    DistilBertModel,
    DistilBertTokenizer,
    CLIPTokenizer,
    CLIPTextModel,
)

MODELS = {
    'openai/clip-vit-base-patch32': (CLIPTextModel, CLIPTokenizer, 512),
    'prajjwal1/bert-tiny': (BertModel, BertTokenizer, 128),
    'prajjwal1/bert-mini': (BertModel, BertTokenizer, 256),
    'prajjwal1/bert-small': (BertModel, BertTokenizer, 512),
    'prajjwal1/bert-medium': (BertModel, BertTokenizer, 512),
    'gpt2': (GPT2Model, GPT2Tokenizer, 768),
    'distilgpt2': (GPT2Model, GPT2Tokenizer, 768),
    'bert-base-uncased': (BertModel, BertTokenizer, 768),
    'bert-large-uncased': (BertModel, BertTokenizer, 1024),
    'roberta-base': (RobertaModel, RobertaTokenizer, 768),
    'roberta-large': (RobertaModel, RobertaTokenizer, 1024),
    'distilbert-base-uncased': (DistilBertModel, DistilBertTokenizer, 768),
    "distilroberta-base": (RobertaModel, RobertaTokenizer, 768),
}

import torch.nn as nn
from transformers import (
    BertModel,
    BertTokenizer,
    GPT2Model,
    GPT2Tokenizer,
    RobertaModel,
    RobertaTokenizer,
    DistilBertModel,
    DistilBertTokenizer,
    CLIPTokenizer,
    CLIPTextModel,
)

MODELS = {
    'openai/clip-vit-base-patch32': (CLIPTextModel, CLIPTokenizer, 512),
    'prajjwal1/bert-tiny': (BertModel, BertTokenizer, 128),
    'prajjwal1/bert-mini': (BertModel, BertTokenizer, 256),
    'prajjwal1/bert-small': (BertModel, BertTokenizer, 512),
    'prajjwal1/bert-medium': (BertModel, BertTokenizer, 512),
    'gpt2': (GPT2Model, GPT2Tokenizer, 768),
    'distilgpt2': (GPT2Model, GPT2Tokenizer, 768),
    'bert-base-uncased': (BertModel, BertTokenizer, 768),
    'bert-large-uncased': (BertModel, BertTokenizer, 1024),
    'roberta-base': (RobertaModel, RobertaTokenizer, 768),
    'roberta-large': (RobertaModel, RobertaTokenizer, 1024),
    'distilbert-base-uncased': (DistilBertModel, DistilBertTokenizer, 768),
    "distilroberta-base": (RobertaModel, RobertaTokenizer, 768),
}

In [2]:
text = "In summary, the add_pooling_layer parameter allows you to control whether you want just the sequence output or both the sequence output and a pooled output. This flexibility lets you tailor the model's outputs to better fit the specific needs of your application."

In [3]:
# type: 'bert-base-uncased'
tokenizer = MODELS['bert-base-uncased'][1].from_pretrained('bert-base-uncased')
text_encoder = MODELS['bert-base-uncased'][0].from_pretrained('bert-base-uncased', add_pooling_layer=False)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'bert.pooler.dense.weight', 'cls.seq_relationship.weight', 'bert.pooler.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [4]:
text_input = tokenizer(text,
                        padding='longest',
                        truncation=True,
                        max_length=30,
                        return_tensors="pt").to('cpu')
text_output = text_encoder(input_ids=text_input.input_ids,
                        attention_mask=text_input.attention_mask)[0]


In [5]:
print(text_input)

{'input_ids': tensor([[  101,  1999, 12654,  1010,  1996,  5587,  1035,  4770,  2075,  1035,
          6741, 16381,  4473,  2017,  2000,  2491,  3251,  2017,  2215,  2074,
          1996,  5537,  6434,  2030,  2119,  1996,  5537,  6434,  1998,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1]])}


In [6]:
text_input.input_ids.shape

torch.Size([1, 30])

In [7]:
print(text_output)

tensor([[[-0.0745, -0.4085, -0.0032,  ..., -0.4064, -0.1115,  0.7753],
         [-0.4994, -0.2811, -0.2728,  ...,  0.0369,  0.7994,  0.7260],
         [ 0.4675, -0.1879, -0.3194,  ...,  0.2579,  0.3036, -0.2950],
         ...,
         [ 0.4218, -0.0810, -0.0760,  ..., -0.0894,  0.0644,  0.3963],
         [-0.5284, -0.7002, -0.5880,  ...,  0.5098,  0.7785, -0.0368],
         [ 0.9336,  0.1749, -0.1502,  ...,  0.2229, -0.5964, -0.2550]]],
       grad_fn=<NativeLayerNormBackward0>)


In [8]:
text_output.shape

torch.Size([1, 30, 768])

In [1]:
2000//512

3

In [1]:
import torch
import torch.nn as nn
from models.audio_encoder import AudioEncoder
from models.text_encoder import TextEncoder
import torch.nn.functional as F
import copy
from tools.losses import AudioTextContrastiveLoss, NTXent
from tools.utils import remove_grad
import ruamel.yaml as yaml
import librosa
import random
import numpy as np
from models.feature_extractor import AudioFeature



config_file_path = './settings/baseline.yaml'

with open(config_file_path, "r") as f:
        config = yaml.safe_load(f)
        
# Load audio signal file
wav_file_path = '../../dac/audio_samples/at2_16khz_cvt.wav'
waveform, _ = librosa.load(wav_file_path, sr=config["audio_args"]["sr"], mono=True)
print('waveform shape before crop: ', waveform.shape)
if config["audio_args"]["max_length"] != 0:
            # if audio length is longer than max_length, we random crop it
            max_length = config["audio_args"]["max_length"] * config["audio_args"]["sr"]
            if waveform.shape[-1] > max_length:
                max_start = waveform.shape[-1] - max_length
                start = random.randint(0, max_start)
                waveform = waveform[start: start + max_length]
                
print('waveform shape: ', waveform.shape)
waveform_tensor = torch.tensor(waveform[None, :])
print('waveform_tensor shape: ', waveform_tensor.shape)

# AF = AudioFeature(config["audio_args"])
# audio_encoded = AF(waveform_tensor)
# print('audio_encoded.shape: ', audio_encoded.shape)

waveform shape before crop:  (240000,)
waveform shape:  (160000,)
waveform_tensor shape:  torch.Size([1, 160000])


In [2]:
import dac
from pathlib import Path


model_path = Path('/home/dhuang/.cache/descript/dac/weights_16khz_8kbps_0.0.5.pth')
# model_path = Path('/home/dhuang/.cache/descript/dac/weights_44khz_8kbps_0.0.1.pth')
audio_enc = dac.DAC.load(model_path)
audio_enc.eval();

In [3]:
x = audio_enc.preprocess(waveform_tensor, 16000)
# x = torch.tensor(x[:,None,:])
x = x[:,None,:].detach().clone()
# print("inputs wav hz is: ", len(inputs[0]) / self.config["audio_args"]["max_length"])
# print("x shape is: ", x.shape)
# time.sleep(10)
# print(f"self.training in eval mode: {not self.training}")
# print(f"self.training.audio_enc in eval mode: {not self.audio_enc.training}")
with torch.no_grad():
    # print("N_CODEBOOKS: ", self.config["audio_encoder_args"]["N_CODEBOOKS"])
    z, codes, latents, _, _ = audio_enc.encode(x, 4)

In [4]:
print(codes.shape)
codes

torch.Size([1, 4, 500])


tensor([[[ 350,    0,  554,  ...,  962,  167,  563],
         [ 501,  268,  327,  ...,  885,  804,  718],
         [ 319,  310,  463,  ...,  450,   14,  715],
         [  84,  422, 1016,  ...,  375,  454,  922]]])

In [5]:
codes_flatten = torch.flatten(codes, start_dim=1)#.to(torch.float)
print(codes_flatten.shape)
batch_size = 3
batch_codes_flatten = codes_flatten.repeat(batch_size, 1)
print(batch_codes_flatten.shape)

torch.Size([1, 2000])
torch.Size([3, 2000])


In [18]:
import torch
from transformers import BertTokenizer, BertModel
import numpy as np

class LongCodesEmbedder(torch.nn.Module):
    def __init__(self, model_name='bert-base-uncased'):
        super(LongCodesEmbedder, self).__init__()
        # self.tokenizer = BertTokenizer.from_pretrained(model_name)
        self.model = BertModel.from_pretrained(model_name)
        self.max_length = 512
        
    @property
    def device(self):
        return list(self.parameters())[0].device

    def forward(self, codes):
        # Tokenize texts without truncation
        # tokens = self.tokenizer(texts, return_tensors='pt', truncation=False, padding=True)
        input_ids = codes # tokens['input_ids']
        # attention_mask = tokens['attention_mask']

        batch_size, seq_len = input_ids.size()

        # Prepare list to collect chunk outputs
        all_chunks = []

        for batch_idx in range(batch_size):
            input_ids_batch = input_ids[batch_idx]
            # attention_mask_batch = attention_mask[batch_idx]

            input_chunks = []
            attention_chunks = []

            # Split input_ids into chunks of max_length with overlap
            chunk_size = self.max_length #- 2  # account for [CLS] and [SEP] tokens
            overlap_size = 50
            
            for i in range(0, len(input_ids_batch), chunk_size - overlap_size):
                chunk_ids = input_ids_batch[i:i + chunk_size]
                # chunk_mask = attention_mask_batch[i:i + chunk_size]
                chunk_mask = torch.tensor([1] * len(chunk_ids)).to(self.device)

                # Add [CLS] and [SEP] tokens
                # chunk_ids = torch.cat([torch.tensor([self.tokenizer.cls_token_id]), chunk_ids, torch.tensor([self.tokenizer.sep_token_id])])
                # chunk_mask = torch.cat([torch.tensor([1]), chunk_mask, torch.tensor([1])])

                # Pad chunks to max_length
                padding_length = self.max_length - chunk_ids.size(0)
                if padding_length > 0:
                    chunk_ids = torch.cat([chunk_ids, torch.tensor([0] * padding_length)])
                    chunk_mask = torch.cat([chunk_mask, torch.tensor([0] * padding_length)])

                input_chunks.append(chunk_ids.unsqueeze(0))
                attention_chunks.append(chunk_mask.unsqueeze(0))

            # Stack chunks into a batch
            input_chunks = torch.cat(input_chunks, dim=0).to(self.device)
            print(input_chunks.shape)
            attention_chunks = torch.cat(attention_chunks, dim=0).to(self.device)
            print(attention_chunks.shape)

            # Process each chunk and collect the hidden states
            outputs = []
            for i in range(input_chunks.size(0)):
                chunk_output = self.model(input_ids=input_chunks[i:i+1], attention_mask=attention_chunks[i:i+1])[0]
                outputs.append(chunk_output)

            # Concatenate all chunk outputs along the sequence dimension
            outputs = torch.cat(outputs, dim=1)
            
            all_chunks.append(outputs.unsqueeze(0))  # Keep batch dimension

        # Stack all batch outputs
        all_chunks = torch.cat(all_chunks, dim=0)

        # Optionally: apply some combination method here (e.g., mean pooling, attention)
        # combined_output = torch.mean(all_chunks, dim=1)  # example of mean pooling
        # Average Pooling
        pooled_embeddings = torch.mean(all_chunks, dim=2, keepdim=True)  # Shape: [1, 1, 768]
        # pooled_embeddings = pooled_embeddings.repeat(1, 1, 4, 1)            # Shape: [1, 4, 768]

        return pooled_embeddings

# Example usage
# model = LongCodesEmbedder()
# texts = np.ndarray([["Your very long text of 2000 tokens goes here...", "Another long text..."]])
# print(texts.shape)
# embeddings = model(texts)


In [19]:
# WITH `combined_output = torch.mean(all_chunks, dim=1)`  # example of mean pooling
model = LongCodesEmbedder()
# texts = np.ndarray([["Your very long text of 2000 tokens goes here...", "Another long text..."]])
# print(texts.shape)
# embeddings = model(texts)

text_output = model(codes_flatten)
print(text_output.shape)
text_output

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


torch.Size([5, 512])
torch.Size([5, 512])
torch.Size([1, 1, 1, 768])


tensor([[[[ 2.6748e-01,  2.9985e-01,  9.8263e-01,  2.2093e-01,  3.5365e-02,
           -5.2790e-01,  5.2103e-01,  2.9357e-02, -2.4657e-01,  1.0981e-01,
            4.5585e-01, -3.2240e-01,  1.2481e-01,  4.0589e-01, -2.3366e-01,
            7.4490e-01, -3.3269e-01,  1.9363e-01, -7.9094e-01,  4.0406e-01,
            1.0193e+00,  5.7548e-01,  2.5680e-01,  8.2678e-01,  3.3883e-01,
            7.9272e-01,  2.9397e-01, -1.0526e+00, -6.0919e-01,  1.7706e-01,
            9.1806e-03,  3.5964e-02,  5.5864e-01, -3.6340e-02, -1.5720e-01,
            1.5364e-02, -3.4198e-01,  1.2270e-01,  3.6486e-01, -1.5424e-01,
           -4.1983e-01, -6.5624e-01,  5.2895e-01,  9.2712e-02,  2.0621e-01,
           -5.3588e-01,  1.3662e-01,  5.6997e-01, -3.7826e-01, -9.0381e-01,
           -7.6079e-01, -2.6866e-03,  6.0744e-01,  3.9286e-02,  2.5605e-01,
            4.3356e-01, -1.0845e-01, -7.4679e-01,  7.8749e-01,  4.0365e-01,
           -5.4367e-01,  4.6030e-01, -9.1697e-01, -1.6975e-01, -1.8310e-01,
            

In [7]:
# Stack all batch outputs, all_chunks WITHOUT `combined_output = torch.mean(all_chunks, dim=1)`  # example of mean pooling
model = LongCodesEmbedder()
# texts = np.ndarray([["Your very long text of 2000 tokens goes here...", "Another long text..."]])
# print(texts.shape)
# embeddings = model(texts)

text_output = model(codes_flatten)
print(text_output.shape)
text_output

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


torch.Size([5, 512])
torch.Size([5, 512])
torch.Size([1, 1, 2560, 768])


tensor([[[[-0.3144, -0.0121,  0.0405,  ..., -0.5311,  0.5728, -0.1658],
          [-0.5853,  0.2675, -0.1129,  ..., -0.8531,  0.3428,  0.0660],
          [-0.6087,  0.2474, -0.0817,  ..., -0.8487,  0.2745,  0.0873],
          ...,
          [ 0.2932,  0.3740,  1.2786,  ..., -0.5581, -0.0460, -1.3185],
          [ 0.0159,  0.3989,  1.0351,  ..., -0.5706, -0.1683, -0.8801],
          [-0.0535,  0.7495,  0.8555,  ..., -0.2349, -0.2308, -1.0645]]]],
       grad_fn=<CatBackward0>)

In [23]:
text_output = model(batch_codes_flatten)
print(text_output.shape)
text_output

torch.Size([5, 512])
torch.Size([5, 512])
torch.Size([5, 512])
torch.Size([5, 512])
torch.Size([5, 512])
torch.Size([5, 512])
torch.Size([3, 1, 2560, 768])


tensor([[[[-0.3144, -0.0121,  0.0405,  ..., -0.5311,  0.5728, -0.1658],
          [-0.5853,  0.2675, -0.1129,  ..., -0.8531,  0.3428,  0.0660],
          [-0.6087,  0.2474, -0.0817,  ..., -0.8487,  0.2745,  0.0873],
          ...,
          [ 0.2932,  0.3740,  1.2786,  ..., -0.5581, -0.0460, -1.3185],
          [ 0.0159,  0.3989,  1.0351,  ..., -0.5706, -0.1683, -0.8801],
          [-0.0535,  0.7495,  0.8555,  ..., -0.2349, -0.2308, -1.0645]]],


        [[[-0.3144, -0.0121,  0.0405,  ..., -0.5311,  0.5728, -0.1658],
          [-0.5853,  0.2675, -0.1129,  ..., -0.8531,  0.3428,  0.0660],
          [-0.6087,  0.2474, -0.0817,  ..., -0.8487,  0.2745,  0.0873],
          ...,
          [ 0.2932,  0.3740,  1.2786,  ..., -0.5581, -0.0460, -1.3185],
          [ 0.0159,  0.3989,  1.0351,  ..., -0.5706, -0.1683, -0.8801],
          [-0.0535,  0.7495,  0.8555,  ..., -0.2349, -0.2308, -1.0645]]],


        [[[-0.3144, -0.0121,  0.0405,  ..., -0.5311,  0.5728, -0.1658],
          [-0.5853,  0.267

In [12]:
# The computation method for tokens dim 
if 2000 - (((2000-462) // 462 ) * 462 + 462) > 0 :
    print(2000+((2000-462) // 462 )*50+462)
else:
    print(2000+((2000-462) // 462 )*50)

2612


In [10]:
print(2560-512)
print((2560-512)//462)

2048
4


In [14]:
512*5

2560

In [15]:
2000//462 + 1

5